// Dummy AI service for development without API keys
class DummyAIService {
  constructor() {
    console.log('✅ Using dummy AI service - no API keys required');
  }

  async generateArticle(aiService, topic, prompt) {
    // Return dummy content for development
    const dummyContent = `
# ${topic}

This is a sample article about ${topic}. In a production environment, this content would be generated by AI.

## Introduction
Catfish are fascinating creatures that play an important role in aquaculture. ${topic} is a crucial aspect of catfish farming and management.

## Key Points
- Understanding ${topic} can improve your catfish farming results
- Proper techniques lead to healthier fish
- Best practices ensure sustainable aquaculture

## Conclusion
${topic} is essential knowledge for any catfish enthusiast or farmer. Continue learning and applying these principles for better results.

*Note: This is placeholder content. Enable AI features by adding API keys to your environment variables.*
    `;

    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    return dummyContent;
  }

  isAIAvailable() {
    return true; // Always available in dummy mode
  }

  getAvailableServices() {
    return ['openai', 'deepseek']; // Show all options
  }
}

export default new DummyAIService();